title: Groonga CloudSearch
permalink: /blog/:year/:month/:day/:title/
author: Groonga CloudSearch project
url: http://gcs.groonga.org
gcs_version: 1.4.0
gcs_release_date: 2012-11-29
gcs_console_version: 1.1.0
